bootstrap = <<SCRIPT
  apt-get update
  apt-get install -y linux-image-extra-virtual git mercurial python-gtk2 python-cairo python-usb python-crypto python-serial python-dev libgcrypt-dev
  hg clone https://bitbucket.org/secdev/scapy-com
  cd scapy-com
  python setup.py install
  cd ..
  git clone https://github.com/adriangranados/killerbee.git
  cd killerbee
  python setup.py install
  cd ..
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/precise64"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "KillerBee"
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
  end

  config.vm.provision "shell", inline: "#{bootstrap}", privileged: true

end
